#Gradle
org.gradle.jvmargs=-Xmx4G
org.gradle.caching=true
org.gradle.configuration-cache=true
org.gradle.daemon=true
org.gradle.parallel=true

#Kotlin
kotlin.daemon.jvmargs=-Xmx4G
kotlin.native.binary.gc=cms
kotlin.incremental.wasm=true
compose.desktop.packaging.checkJdkVendor=false
org.gradle.java.installations.auto-detect=true
org.gradle.java.installations.auto-download=false
olcbox.version=0.0.14
olcbox.build=2026092406
olcbox.versionCode=2026092406
olcbox.olcrtcSha=d7a00da5242f72a48b505ffc4b6aa8246376bf25
olcbox.awgCoreSha=7745e9afd0a1f7a5b6216fd114e1ad4a64b974c3
olcbox.awgWireguardSha=b311c8ac53aed5637b0bd961b9c6ae1fc1eef093
olcbox.xrayVersion=26.3.27
olcbox.xraySha=d2758a023cd7f4174a5a5fa4ff66e487d4342ba0
olcbox.openFluxSha=d34dc8caa70ca059cd80d8f5753499361052dabc

#Android
android.useAndroidX=true
android.r8.failOnMissingKotlinMetadata=false
kotlin.metadata.ignore.unsupported=true

# AGP 9.0+ performance and cleanup
android.generateSyncIssueWhenLibraryConstraintsAreEnabled=false
