package org.olcbox.app.ui.theme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

internal val OlcboxDarkColorScheme = darkColorScheme(
    primary = Color(0xFFE8C18D),
    onPrimary = Color(0xFF41280B),
    primaryContainer = Color(0xFF5C3B18),
    onPrimaryContainer = Color(0xFFFFDDB6),
    inversePrimary = Color(0xFF77512A),
    secondary = Color(0xFFD4C4AF),
    onSecondary = Color(0xFF382E23),
    secondaryContainer = Color(0xFF504538),
    onSecondaryContainer = Color(0xFFF1DEC6),
    tertiary = Color(0xFFB8C7CF),
    onTertiary = Color(0xFF23333A),
    tertiaryContainer = Color(0xFF394A52),
    onTertiaryContainer = Color(0xFFD4E4EC),
    background = Color(0xFF15110C),
    onBackground = Color(0xFFEDE1D2),
    surface = Color(0xFF15110C),
    onSurface = Color(0xFFEDE1D2),
    surfaceVariant = Color(0xFF4D453A),
    onSurfaceVariant = Color(0xFFD2C4B4),
    surfaceContainerLowest = Color(0xFF0F0A06),
    surfaceContainerLow = Color(0xFF1E1912),
    surfaceContainer = Color(0xFF282219),
    surfaceContainerHigh = Color(0xFF332C22),
    surfaceContainerHighest = Color(0xFF40372C),
    inverseSurface = Color(0xFFEDE1D2),
    inverseOnSurface = Color(0xFF322B22),
    outline = Color(0xFF9B8E7D),
    outlineVariant = Color(0xFF4D453A),
    error = Color(0xFFFFB4AB),
    onError = Color(0xFF690005),
    errorContainer = Color(0xFF93000A),
    onErrorContainer = Color(0xFFFFDAD6)
)

internal val OlcboxLightColorScheme = lightColorScheme(
    primary = Color(0xFF77512A),
    onPrimary = Color(0xFFFFFFFF),
    primaryContainer = Color(0xFFFFDDB6),
    onPrimaryContainer = Color(0xFF2A1702),
    inversePrimary = Color(0xFFE8C18D),
    secondary = Color(0xFF675A49),
    onSecondary = Color(0xFFFFFFFF),
    secondaryContainer = Color(0xFFF1DEC6),
    onSecondaryContainer = Color(0xFF21180E),
    tertiary = Color(0xFF536873),
    onTertiary = Color(0xFFFFFFFF),
    tertiaryContainer = Color(0xFFD7E4EB),
    onTertiaryContainer = Color(0xFF0F1F27),
    background = Color(0xFFFFF8EF),
    onBackground = Color(0xFF201A13),
    surface = Color(0xFFFFF8EF),
    onSurface = Color(0xFF201A13),
    surfaceVariant = Color(0xFFEDE0CF),
    onSurfaceVariant = Color(0xFF4D453A),
    surfaceContainerLowest = Color(0xFFFFFFFF),
    surfaceContainerLow = Color(0xFFFCF0E3),
    surfaceContainer = Color(0xFFF7E8D7),
    surfaceContainerHigh = Color(0xFFF1E0CD),
    surfaceContainerHighest = Color(0xFFEAD8C3),
    inverseSurface = Color(0xFF362F26),
    inverseOnSurface = Color(0xFFFFF1E2),
    outline = Color(0xFF7F7262),
    outlineVariant = Color(0xFFD2C4B4),
    error = Color(0xFFBA1A1A),
    onError = Color(0xFFFFFFFF),
    errorContainer = Color(0xFFFFDAD6),
    onErrorContainer = Color(0xFF410002)
)
